[project]
name = "bluroma"
version = "0.1.0"
authors = [
    {name = "penny", email = "penny@noob.quest"},
]
description = "A Pleroma/Akkoma-like Bluesky client."
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.11.2"